### ISSUE TITLE
Feature: allow usage of systemd provided state directory as fs storage path

### ISSUE THREAD

**Issue by mxrth** [chronos-tachyon/roxy#2]
**Use Case:**

Systemd provides the ["StateDirectory=" directive](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RuntimeDirectory=) which sets the `$STATE_DIRECTORY` environment variable  to a systemd managed persistent directory (for example systemd ensures that it has the right permissions if the service file uses the DynamicUser facilities).

It would be nice to be able to use this as the storage directory for the file system storage.

**Possible Implementation:**

The simplest implementation enabling this use case would be to expand environment-variables in fs:path (for example via `os.ExpandEnv()`)
Other possibilities include doing this expansion for all configuration values or handling the case of systemd explicitly as part of the fs storage driver (e.g. activly looking for `$STATE_DIRECTORY `and possibly `$CREDENTIALS_DIRECTORY` introduced in systemd  247.)

If you have a preferred solution I would be happy to open a corresponding pull request :)

**Comment by chronos-tachyon** [comment]
Fixed in [v0.2.3](https://github.com/chronos-tachyon/roxy/releases/tag/v0.2.3).
